### ISSUE TITLE
Are modulus and exponent supposed to come from the private key?

### ISSUE THREAD

**Issue by cullylarson** [Levino/mock-jwks#19]
This might be a dumb question; I don't know much about JWKs. I want to confirm something that seemed odd to me. In `tools.js::createJWKS` the modulus and exponent are generated from the private key. Since those values are then made publicly available, I wanted to make sure that was intentional and that the modulus and exponent can't be used to somehow obtain the private key. I tried searching the web for information about which key should be used to generate `n` and `e`, but couldn't find a clear answer. Thanks!

```js
const helperKey = new NodeRSA()
helperKey.importKey(forge.pki.privateKeyToPem(privateKey))
const { n: modulus, e: exponent } = helperKey.exportKey('components')
```

**Comment by Levino** [comment]
I do not know. The tests pass and one can use it. This is not a production library. Possibly the strength of the signatures is zero. Does not matter. It is a testing tool.

**Comment by cullylarson** [comment]
Btw, I just tried this using the public key instead, and it worked. It looks like:

```js
const helperKey = new NodeRSA()
helperKey.importKey(forge.pki.publicKeyToPem(publicKey))
const { n: modulus, e: exponent } = helperKey.exportKey('components-public')
```

**Comment by cullylarson** [comment]
Btw, for anyone visiting this issue in the future, the public modulus and exponent should be used, not the private (modulus is actually shared, so it's the same in any case). The only reason the code in the repo works, using the private key, is that the `exportKey` function in `node-rsa` always returns the public exponent as `e`, whether you export the public components or private.

**Comment by Levino** [comment]
I would say: Usually you just do not have the private key because you want to verify the signature on the server. I was taking shortcuts because this all is just a simulation but @cullylarson is right. When in doubt, take it from the public key.

**Comment by cullylarson** [comment]
@Levino You do need the private key on the server to generate the JWTs. And you need the private key to create the certificate used to set `x5c` in the JWKS endpoint. Also, in this case it isn't a matter of "when it doubt"; you just certainly should not use the private key's exponent. It can be used to re-create the private key.

**Comment by Levino** [comment]
Interesting. TIL.
