### ISSUE TITLE
Consider adding a LICENSE.md

### ISSUE THREAD

**Issue by slifty** [levino/mock-jwks#219]
The package.json specifies an MIT license but it might be helpful to also add a LICENSE.md file in the repository just to make it more explicit / tie into github's magic.

**Comment by levino** [comment]
Thank you for the suggestion.

Why not? Feel free to open a PR which implements these changes.

**Comment by levino** [comment]
Since there was no more activity here, I will close this issue. Let me know if still relevant.

**Comment by slifty** [comment]
Apologies!  I'll open the PR now (no need to re-open the issue of course)

**Comment by levino** [comment]
Thank you!
