### ISSUE TITLE
[v0.3.3] Cannot find module 'superagent'

### ISSUE THREAD

**Issue by flo-sch** [Levino/mock-jwks#48]
Hey,

I just upgraded `mock-jwks` from 0.3.2 to 0.3.3 but tests no longer work after it:

> Cannot find module 'superagent' from 'node_modules/mock-jwks/build/index.js'

superagent was referenced as a dependency until at least [v0.3.1](https://github.com/Levino/mock-jwks/blob/v0.3.1/package.json#L100), and I think it was still there at v0.3.2 (seems like the git tag for v0.3.2 has not been created?)

I am not sure why is it referenced in the dist files though, since I do not find any direct reference to it in the `src` folder here  🤷‍♂️
This is what the v0.3.3 compiled code shows:

```js
// node_modules/mock-jwks/build/index.js
// ...
// L72
var nock_1 = __importDefault(require("nock"));
var request = __importStar(require("superagent"));
var url_1 = __importDefault(require("url"));
var tools_1 = require("./tools");
var createJWKSMock = function (jwksOrigin, jwksPath) {
  // ...
}
```

Is it intentional and we need to add it as a devDependency (perhaps it could be good to set it as a peerDependency in that case and/or mention it in the README)?

**Comment by flo-sch** [comment]
According to this commit, it should not be referenced anymore, perhaps is it just a "broken" release then?
(forgot to run `yarn build` before?)

**Comment by Levino** [comment]
I removed and rebuild the `build` folder. Did it help? @0.3.4

**Comment by Levino** [comment]
Tag for 0.3.2 https://github.com/Levino/mock-jwks/releases/tag/0.3.2

**Comment by Levino** [comment]
Releasing with `yarn@berry` is somewhat different from `yarn@classic`. Somehow messed something up along the way. Falling back to `npm version patch` which also creates the git commit and tag automatically. (Kind of a note so myself).

**Comment by flo-sch** [comment]
v0.3.5 works fine indeed, thanks for the quick fix 🎉

**Comment by flo-sch** [comment]
I have not tried `yarn@berry` yet, was v0.3.2 your first with berry?

It seems that, starting from v0.3.2, versions have no longer be defined as "[releases](https://github.com/Levino/mock-jwks/releases)" but as "[tags](https://github.com/Levino/mock-jwks/tags)" instead - on GitHub only, no visible difference on npmjs.org though from what I can see -

Oh btw, small detail but since I noticed it, the [`@types/superagent` dependency](https://github.com/Levino/mock-jwks/blob/v0.3.5/package.json#L72) can probably be removed as well I think?
