### ISSUE TITLE
Error with npm@7 and nock@13

### ISSUE THREAD

**Issue by Levino** [Levino/mock-jwks#51]
We currently only support `nock@11` as a peerDependency. If one uses `npm@7` and `nock@13` in a project and installs `mock-jwks` as a dependency, one gets an error. At least it looks like this is what @JSanchezIO experiences in his project and made him create #50.

**Comment by Levino** [comment]
I think we have two possible solutions:
1. We could relax the constraint for the version of `nock` we support as a peer dependency as suggested in #50. This will create some overhead as we have to run the tests three times for each individual version of `nock`. But it would also mean that the following release is a patch and not a breaking change.
2. We could just bump `nock` to `13`. This would be dead simple but would be a breaking change for our users and potentially annoying if people have to change complicated code in order to support `nock@13` in their project.

I would prefer the first approach. Does anyone have another solution? Also please keep in mind that `nock` must be a peer dependency and cannot be a depedendency and just be "shipped along `mock-jkws`" as I have explained in https://github.com/Levino/mock-jwks/issues/35#issuecomment-773896646 .

**Comment by JSanchezIO** [comment]
I like the idea of option 1, but I'm unsure as to how we can run the tests for each major version of `nock` that we'd like to support. Option 2 sounds easier on our end but does sound like it hinders consumers as they'd be forced to update `nock` to continue using this package.
