### ISSUE TITLE
mock-jwks can't be used with all OpenId implementations

### ISSUE THREAD

**Issue by aschekatihin** [Levino/mock-jwks#8]
createJWKSMock needs a parameter to control whether it should add '/.well-known/jwks.json' or not. Some openid implementations use different url. 
For example for keycloak it is: http://{host}/auth/realms/{realm}/protocol/openid-connect/certs

**Comment by Levino** [comment]
Could be given a second, optional argument.
Instead of https://github.com/Levino/mock-jwks/blob/af2725c006002101b072becb8dd9008723155df1/index.ts#L12
It could go like:
```typescript
const createJWKSMock = (jwksHost: string, overrides?: { certPath: string} = { certPath: '/.well-known/jwks.json'}): JWKSMock => ...
```
Or something alike. Not sure about the Typescript syntax for optional arguments right now. Do you want to open a PR @aschekatihin ?

**Comment by aschekatihin** [comment]
Yes, something like this. 
I will create a PR a bit later

**Comment by aschekatihin** [comment]
#9

**Comment by aschekatihin** [comment]
It looks a bit excessive taking into account first parameter isn't used:

```
const server = createApp({
      jwksHost: 'https://hardfork.eu.auth0.com/',
      jwksUri: 'https://hardfork.eu.auth0.com/protocol/openid-connect/certs',
    }).listen()
```

**Comment by Levino** [comment]
Please comment on the proposed solution in the PR #10 and only comment on the issue here.

**Comment by Levino** [comment]
Fixed in https://github.com/Levino/mock-jwks/releases/tag/v0.1.9
